Complete Build Script for CSS
lpzchrstn/sass-lpzchrstn pull request #1
Opened 2022-01-05 10:03 UTC by lpzchrstn

# Finished Build Script for CSS
This PR contains these additional features:
- A package.json file containing the dependencies and the scripts for bundling css:
  - Build Script
  - Prod Script
  - Watch Script

Note: all scss files should be imported in `src/scss/style.scss`

2022-01-06 16:41 UTC, joshuacerbito requested changes
I left a few comments on some of the files.
Please make sure to respond to those as you address the comments for each.

2022-01-06 16:41 UTC, joshuacerbito commented on package.json
> +    "watching-css": "sass --watch ./src/scss/styles.scss:./dist/css/styles.css",
I noticed that `watching-css` is only being used on `watch-css`, which means the entire command can be added to line 9. It might result to a longer line, but that'll reduce the amount of executable scripts in the CLI.

Also, since these are commands that we run in the terminal, it's always better to give them names that start with verbs. `prod` is a notable exception to this rule, though technically it's non-standard.

2022-01-06 16:41 UTC, joshuacerbito commented on src/js/scripts.js
> +console.log(transportation);
I think this is for a different challenge, no?
But since it's already here: Always delete commented-out codes (e.g. line 35-43 and line 64-71) before opening PRs. If it's something important that you want to save, you can always add those to a commit, then remove it on another commit before opening a PR, that way it's still in the git history, safely versioned.

2022-01-07 01:29 UTC, lpzchrstn commented on package.json
> +    "watching-css": "sass --watch ./src/scss/styles.scss:./dist/css/styles.css",
Both of these are noted.

2022-01-07 01:34 UTC, lpzchrstn commented on src/js/scripts.js
> +console.log(transportation);
Yes this is for a different challenge, I just copied and pasted it to test if the js bundler works and left it so that whenever somebody needs to test it, there are some scripts that can be bundled.

But I'll still keep in mind about what you said for he commented codes.

2022-01-11 12:24 UTC, joshuacerbito requested changes
Hi, @lpzchrstn. Please make sure to untrack/delete the `dist` files and then add `dist` to the `.gitignore` file. Do note that you first have to create a commit deleting the `dist` files, and create another commit updating the `.gitignore` file.

2022-01-13 12:32 UTC, joshuacerbito reviewed
Everything looks good. Just don't forget to leave comments and close loop on the conversations as you update the PR, so it doesn't look like the conversation's been abandoned

2022-01-13 12:33 UTC, merged