Js build
lpzchrstn/sass-lpzchrstn pull request #2
Opened 2022-01-05 10:07 UTC by lpzchrstn

# Finished Build Script for JS
This PR contains these additional features:
- A package.json file containing the dependencies and the scripts for bundling js:
  - Build Script
  - Prod Script
  - Watch Script
  - Rollup Configuration Script
  - Rollup Configuration Script for prod

## Notes:
- The build, prod and watch script can be viewed in #1
- All js files should be imported in `src/js/scripts.js`

2022-01-06 18:54 UTC, joshuacerbito requested changes
Please review my comments from the [other PR](https://github.com/lpzchrstn/sass-lpzchrstn/pull/1) as those are also applicable to this PR.

Also, we don't include compiled assets to the repo (e.g. the `dist` files) since that cause a lot of conflicts especially when working with other developers. Please untrack the `dist` files, and then update `.gitignore` and ignore everything inside the `dist` folder.

2022-01-07 02:03 UTC, lpzchrstn commented
> Please review my comments from the [other PR](https://github.com/lpzchrstn/sass-lpzchrstn/pull/1) as those are also applicable to this PR.
> 
> Also, we don't include compiled assets to the repo (e.g. the `dist` files) since that cause a lot of conflicts especially when working with other developers. Please untrack the `dist` files, and then update `.gitignore` and ignore everything inside the `dist` folder.

Done adding changes for this.

2022-01-11 12:28 UTC, joshuacerbito requested changes

2022-01-11 12:28 UTC, joshuacerbito commented on .gitignore
> +dist/
Please always add an empty line at the end of every file

2022-01-13 13:09 UTC, joshuacerbito requested changes
Everything looks good except for the Merge Conflicts.
Please fix the conflicts first, then this PR's good for merging.

2022-01-14 01:42 UTC, lpzchrstn commented
> Everything looks good except for the Merge Conflicts. Please fix the conflicts first, then this PR's good for merging.

Fixed the Merge Conflict.

2022-01-26 16:37 UTC, merged